### ISSUE TITLE
Got No parameterless constructor error webgl, none stripped alreay set

### ISSUE THREAD

**Issue by johnny0618** [Nethereum/Nethereum.Flappy#3]
“No parameterless constructor defined for Nethereum.Unity.RpcModel.RpcParametersJsonConverter”.

Unity 2019.1.11 Webgl
Strip Enginee Code unckecked
Managed Stripping Level low

"When compiling to Webgl or IOS, you need to ensure that dlls are not stripped when running IL2CPP"

What else do I need to do make it works?Thank you

**Comment by juanfranblanco** [comment]
Just make sure you put the link.xml file in your assets folder https://github.com/Nethereum/Nethereum.Flappy/blob/master/link.xml

**Comment by juanfranblanco** [comment]
If you want a template with the latest dlls to get started check https://github.com/Nethereum/Unity3dSimpleSampleNet461

**Comment by johnny0618** [comment]
Thank you ,I am trying now

**Comment by johnny0618** [comment]
Working perfectly,Great!
